import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PlasmicHomepage } from "../components/plasmic/blank_project/PlasmicHomepage";

export default function Home({todos}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <PlasmicHomepage />
         <div>
          {todos.map((item) => (
            <p key={item.id}>{item.title}</p>
          ))}
         </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const todos = await res.json();
  return {
    props: {
      todos,
    },
  };
  
};
